name: RShiny App Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up R environment
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1' # Use the appropriate R version for your app

    # Install system dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

    # Install devtools and dependencies
    - name: Install devtools and dependencies
      run: |
        install.packages('devtools', repos = 'https://cloud.r-project.org/')
        devtools::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    # Run Shiny tests
    - name: Run Shiny tests
      run: |
        if (!requireNamespace('shinytest2', quietly = TRUE)) install.packages('shinytest2', repos = 'https://cloud.r-project.org/')
        shinytest2::test_app()
      shell: Rscript {0}

    # Save test results (if using testthat or shinytest2)
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: shiny-test-results
        path: .github/workflows/logs/*.Rout
